<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: C:\Users\ASUS\kn24_php\src\templates\_footer.latte */
final class Template_9a564f9638 extends Latte\Runtime\Template
{
	public const Source = 'C:\\Users\\ASUS\\kn24_php\\src\\templates\\_footer.latte';


	public function main(array $ʟ_args): void
	{
		echo '<footer>
    <div class="footer-content">
        <div class="footer-section">
            <p>Сучасний веб-додаток з красивим дизайном</p>
        </div>
        
        <div class="footer-section">
            <p>&copy; ';
		echo LR\Filters::escapeHtmlText(date('Y')) /* line 8 */;
		echo ' Всі права захищені</p>
        </div>
        
        <div class="footer-section">
            <p>Створено з ❤️ використовуючи PHP та Latte</p>
        </div>
    </div>
</footer>';
	}
}
