<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: C:\Users\ASUS\kn24_php\src\templates\_nav.latte */
final class Template_e974bdb74b extends Latte\Runtime\Template
{
	public const Source = 'C:\\Users\\ASUS\\kn24_php\\src\\templates\\_nav.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<nav class="nav">
    <div class="nav-links">
        <a href="/" class="nav_link">Головна</a>
    </div>
    <div class="nav-links">
        <a href="/game" class="nav_link">Ігри</a>
    </div>
    
    <div class="nav-links">
';
		if ($user) /* line 10 */ {
			echo '            <a href="/logout?token=';
			echo LR\Filters::escapeHtmlAttr($csrf_token) /* line 11 */;
			echo '" class="nav_link" 
               onclick="return confirm(\'Ви впевнені, що хочете вийти?\')">Logout</a>
';
		} else /* line 13 */ {
			echo '            <a href="/login" class="nav_link">Sign In</a>
            <a href="/reg" class="nav_link">Sign Up</a>
';
		}
		echo '    </div>
</nav>  ';
	}
}
