<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: C:\Програми\2year\№5\kn24_php\src\Classes\..\templates\login.latte */
final class Template_642d1f2ceb extends Latte\Runtime\Template
{
	public const Source = 'C:\\Програми\\2year\\№5\\kn24_php\\src\\Classes\\..\\templates\\login.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '    <h1>Нижче у нас форма, яка буде передавати дані на сервер методом POST</h1>
    
';
		if (isset($error)) /* line 3 */ {
			echo '        <div class="error-message">
            ';
			echo LR\Filters::escapeHtmlText($error) /* line 5 */;
			echo '
        </div>
';
		}
		echo '    
    <form method="POST" action="/login">
        <label for="login"></label>
        <input 
            type="text" 
            name="login" 
            id="login" 
            placeholder="login" 
            required
            />
        <label for="password"></label>
        <div class="password-container">
            <input 
                type="password" 
                name="password" 
                id="password" 
                placeholder="password" 
                required
            />
            <button 
                type="button" 
                id="togglePassword" 
            >
                👁️
            </button>
        </div>
        <input type="submit" value="Авторизуватись">
    </form>

    <script>
        togglePassword = () => {
            const passwordInput = document.getElementById(\'password\');
            const toggleButton = document.getElementById(\'togglePassword\');
            
            if (passwordInput.type === \'password\') {
                passwordInput.type = \'text\';
                toggleButton.textContent = \'🙈\';
                toggleButton.title = \'Сховати пароль\';
            } else {
                passwordInput.type = \'password\';
                toggleButton.textContent = \'👁️\';
                toggleButton.title = \'Показати пароль\';
            }
        }
        
        // Додаємо підказку при завантаженні
        document.addEventListener(\'DOMContentLoaded\', () => {
            let btn = document.getElementById(\'togglePassword\');
            btn.title = \'Показати пароль\';
            btn.addEventListener(\'click\', togglePassword);
        })
    </script>';
	}
}
